package roulette.game.constant;
public enum ErrorCodes {
    CREATE_NEW_ROULETTE,
    OPEN_ROULETTE,
    NOT_PRESENT_HEADER_USER_ID,
    THE_BET_NUMBER_NOT_IS_VALID,
    THE_BET_VALUE_NOT_IS_VALID,
    NOT_EXIST_ROULETTE_VALID_FOR_THE_BET,
    THE_ROULETTE_NOT_IS_OPEN;
}
